export var REQUEST_ASYNC = '@@query/REQUEST_ASYNC';
export var REQUEST_START = '@@query/REQUEST_START';
export var REQUEST_SUCCESS = '@@query/REQUEST_SUCCESS';
export var REQUEST_FAILURE = '@@query/REQUEST_FAILURE';
export var CANCEL_QUERY = '@@query/CANCEL_QUERY';
export var MUTATE_ASYNC = '@@query/MUTATE_ASYNC';
export var MUTATE_START = '@@query/MUTATE_START';
export var MUTATE_SUCCESS = '@@query/MUTATE_SUCCESS';
export var MUTATE_FAILURE = '@@query/MUTATE_FAILURE';
export var RESET = '@@query/RESET';
export var REMOVE_ENTITIES = '@@query/REMOVE_ENTITIES';
export var REMOVE_ENTITY = '@@query/REMOVE_ENTITY';
//# sourceMappingURL=action-types.js.map